// import "./App.css";
import "@mantine/core/styles.css";
import { Layout } from "./components/custom-layout";
import { createHand } from "./helpers/createHands";
function App() {
  return (
    <Layout>
      {createHand([
        "Z5",
        "Z5",
        "Z5",
        "Z6",
        "Z6",
        "Z6",
        "Z7",
        "Z7",
        "P1",
        "P1",
        "P2",
        "P2",
        "P3",
      ])}
      {createHand([
        "S2",
        "S3",
        "S4",
        "S4",
        "S5",
        "S6",
        "M6",
        "M7",
        "M8",
        "P1",
        "P1",
        "P2",
        "P3",
      ])}
      {createHand([
        "Z5",
        "Z5",
        "Z5",
        "Z6",
        "Z6",
        "Z6",
        "Z7",
        "Z7",
        "P1",
        "P1",
        "P2",
        "P2",
        "P3",
      ])}
      {createHand([
        "Z5",
        "Z5",
        "Z5",
        "Z6",
        "Z6",
        "Z6",
        "Z7",
        "Z7",
        "P1",
        "P1",
        "P2",
        "P2",
        "P3",
      ])}
      {createHand([
        "Z5",
        "Z5",
        "Z5",
        "Z6",
        "Z6",
        "Z6",
        "Z7",
        "Z7",
        "P1",
        "P1",
        "P2",
        "P2",
        "P3",
      ])}
      {createHand([
        "Z5",
        "Z5",
        "Z5",
        "Z6",
        "Z6",
        "Z6",
        "Z7",
        "Z7",
        "P1",
        "P1",
        "P2",
        "P2",
        "P3",
      ])}
      {createHand([
        "Z5",
        "Z5",
        "Z5",
        "Z6",
        "Z6",
        "Z6",
        "Z7",
        "Z7",
        "P1",
        "P1",
        "P2",
        "P2",
        "P3",
      ])}
      {createHand([
        "Z5",
        "Z5",
        "Z5",
        "Z6",
        "Z6",
        "Z6",
        "Z7",
        "Z7",
        "P1",
        "P1",
        "P2",
        "P2",
        "P3",
      ])}
      {createHand([
        "Z5",
        "Z5",
        "Z5",
        "Z6",
        "Z6",
        "Z6",
        "Z7",
        "Z7",
        "P1",
        "P1",
        "P2",
        "P2",
        "P3",
      ])}
    </Layout>
  );
}

export default App;
